#!/usr/bin/env python3
"""Build the curated Gate 4 extraction matrix and close second-pass screening."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any, Mapping


ROOT = Path(__file__).resolve().parents[1]
LITERATURE = ROOT / "literature"

FIELDS = (
    "evidence_id",
    "citation",
    "year",
    "evidence_type",
    "mission_and_task",
    "dynamics_fidelity",
    "objective_and_constraints",
    "uncertainty_treatment",
    "input_data_and_availability",
    "classical_algorithm",
    "quantum_algorithm",
    "quantum_resources",
    "optimizer_and_tuning",
    "split_and_leakage_controls",
    "classical_baselines",
    "primary_metrics",
    "uncertainty_and_statistics",
    "hardware_vs_simulation",
    "code_availability",
    "failure_reporting",
    "reported_limitations",
    "gate4_implication",
    "quality_data_provenance",
    "quality_physics_mission_fidelity",
    "quality_baseline_fairness",
    "quality_split_leakage",
    "quality_statistical_uncertainty",
    "quality_quantum_resource_reporting",
    "quality_hardware_realism",
    "quality_reproducibility",
    "quality_claim_calibration",
    "source_url",
    "doi",
    "screening_status",
)


def evidence(
    evidence_id: str,
    citation: str,
    year: int,
    evidence_type: str,
    mission_and_task: str,
    source_url: str,
    doi: str = "",
    **values: Any,
) -> dict[str, Any]:
    row: dict[str, Any] = {field: "unclear" for field in FIELDS}
    row.update(
        {
            "evidence_id": evidence_id,
            "citation": citation,
            "year": year,
            "evidence_type": evidence_type,
            "mission_and_task": mission_and_task,
            "source_url": source_url,
            "doi": doi,
            "screening_status": "included_primary_or_authoritative_record",
            "quality_data_provenance": "partial",
            "quality_physics_mission_fidelity": "not_applicable",
            "quality_baseline_fairness": "partial",
            "quality_split_leakage": "unclear",
            "quality_statistical_uncertainty": "partial",
            "quality_quantum_resource_reporting": "not_applicable",
            "quality_hardware_realism": "not_applicable",
            "quality_reproducibility": "partial",
            "quality_claim_calibration": "partial",
        }
    )
    row.update(values)
    return row


RECORDS = [
    evidence(
        "E001",
        "Woffinden, Eckman, and Robinson, Optimized Trajectory Correction Burn Placement for the NASA Artemis II Mission",
        2023,
        "NASA primary mission-design research",
        "Artemis II robust correction-burn placement",
        "https://ntrs.nasa.gov/api/citations/20230000223/downloads/Artemis2OptTrajDesignFinal.pdf",
        dynamics_fidelity="Integrated cislunar GN&C linear covariance model with maneuver, navigation, venting, and crew-timeline effects",
        objective_and_constraints="Genetic optimization of nominal plus 3-sigma OTC2-RTC3 delta-v; EI ellipse, lunar altitude, burn timing, and optional crew-sleep penalties",
        uncertainty_treatment="Linear covariance propagation of environment, navigation, measurement, process, and actuator uncertainty",
        input_data_and_availability="Public paper exposes selected assumptions and bounds; mission-owned implementation and full covariance are unavailable",
        classical_algorithm="Linear covariance analysis embedded in a genetic algorithm",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="GA population 60 and 15 generations; authors state runtime motivated the compromise",
        split_and_leakage_controls="not_applicable; not a learned surrogate study",
        classical_baselines="Notional burn schedule and three optimization formulations",
        primary_metrics="Robust total correction delta-v and entry-interface dispersion margins",
        uncertainty_and_statistics="Covariance-based 3-sigma analysis; no public flight covariance or distributional validation",
        hardware_vs_simulation="Mission-design simulation only",
        code_availability="not_public",
        failure_reporting="Constraint penalties and runtime limitations described",
        reported_limitations="Notional preflight Artemis II analysis; mission-owned details are unavailable",
        gate4_implication="Defines the primary target, hard constraints, uncertainty variables, and strong numerical reference",
        quality_data_provenance="strong",
        quality_physics_mission_fidelity="strong",
        quality_baseline_fairness="partial",
        quality_split_leakage="not_applicable",
        quality_statistical_uncertainty="strong",
        quality_reproducibility="partial",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E002",
        "De Grossi et al., Transcription and Optimization of an Interplanetary Trajectory through Quantum Annealing",
        2025,
        "primary quantum optimization research",
        "Earth-Mars low-thrust trajectory transcription and optimization",
        "https://link.springer.com/article/10.1007/s42064-024-0216-6",
        "10.1007/s42064-024-0216-6",
        dynamics_fidelity="Pseudospectral low-thrust optimal-control transcription",
        objective_and_constraints="Binary transcription of dynamics and trajectory objective into QUBO form",
        uncertainty_treatment="not_reported_as_primary_design",
        input_data_and_availability="Paper problem instances; open article",
        classical_algorithm="Linearization, pseudospectral transcription, and hybrid classical-quantum solvers",
        quantum_algorithm="D-Wave quantum annealing; this is optimization, not QML",
        quantum_resources="Fully quantum and hybrid annealers; implementable dimensions and hardware limits discussed",
        optimizer_and_tuning="Binary representation and penalty construction are central design choices",
        split_and_leakage_controls="not_applicable",
        classical_baselines="Hybrid and fully quantum solver comparisons; no replacement for supervised QML baselines",
        primary_metrics="Trajectory objective and constraint satisfaction",
        uncertainty_and_statistics="No confirmatory learned-model seed analysis",
        hardware_vs_simulation="D-Wave hardware plus hybrid solvers",
        code_availability="not_verified_public",
        failure_reporting="Current hardware dimensional limits explicitly discussed",
        reported_limitations="Earth-Mars case; annealing result cannot establish QML or cislunar advantage",
        gate4_implication="Keep annealing/QAOA outside the registered QML benchmark",
        quality_physics_mission_fidelity="partial",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E003",
        "Bowles, Ahmed, and Schuld, Better than Classical? The Subtle Art of Benchmarking Quantum Machine Learning Models",
        2024,
        "primary QML benchmark",
        "Fair comparison of 12 QML models on 160 classical-data classification datasets",
        "https://arxiv.org/abs/2403.07059",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Classification benchmark with controlled experimental design",
        uncertainty_treatment="Multiple datasets and architectures; no spacecraft uncertainty",
        input_data_and_availability="Six tasks generating 160 datasets; open benchmark package",
        classical_algorithm="Out-of-the-box classical ML comparators",
        quantum_algorithm="Popular variational and kernel QML classifiers",
        quantum_resources="Classical quantum simulation at small scales; entanglement ablations",
        optimizer_and_tuning="Systematic model study with architecture comparisons",
        split_and_leakage_controls="Registered benchmark splits in open package",
        classical_baselines="Strong ordinary classical models",
        primary_metrics="Classification performance across datasets",
        uncertainty_and_statistics="Cross-dataset comparison; negative outcomes retained",
        hardware_vs_simulation="Quantum simulation; no hardware-speedup claim",
        code_availability="public",
        failure_reporting="Reports classical wins and cases where removing entanglement does not hurt",
        reported_limitations="Small synthetic/classical tasks and simulation do not establish practical quantum advantage",
        gate4_implication="Require unrestricted classical baselines, entanglement ablation, and negative-result reporting",
        quality_data_provenance="strong",
        quality_baseline_fairness="strong",
        quality_split_leakage="strong",
        quality_statistical_uncertainty="strong",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="partial",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E004",
        "Skolik, Jerbi, and Dunjko, Quantum Agents in the Gym: A Variational Quantum Algorithm for Deep Q-Learning",
        2022,
        "primary variational QRL research",
        "Deep Q-learning on discrete and continuous-state Gym tasks",
        "https://quantum-journal.org/papers/q-2022-05-24-720/",
        "10.22331/q-2022-05-24-720",
        dynamics_fidelity="Generic control environments, not spacecraft dynamics",
        objective_and_constraints="Q-value learning under benchmark task rewards",
        uncertainty_treatment="Training stochasticity and architecture sensitivity",
        input_data_and_availability="Benchmark environments and public paper/code context",
        classical_algorithm="Deep Q-network",
        quantum_algorithm="Parameterized quantum-circuit Q-learning",
        quantum_resources="Encoding, observables, PQC architecture, and simulation conditions reported",
        optimizer_and_tuning="Extensive PQC and neural-network hyperparameter search with parameter comparisons",
        split_and_leakage_controls="Environment evaluation; not a held-out regression split",
        classical_baselines="Classical DQN with varying parameter counts",
        primary_metrics="Task return and success",
        uncertainty_and_statistics="Architecture choices dominate parameter count in reported tasks",
        hardware_vs_simulation="Quantum simulation",
        code_availability="public_or_linked",
        failure_reporting="Ablates encoding/readout and discusses restricted separation claims",
        reported_limitations="Simple Gym tasks; no spacecraft or hardware advantage",
        gate4_implication="Use matched classical capacity, fixed observables, encoding ablations, and no control claim in Phase 1",
        quality_baseline_fairness="strong",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="partial",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E005",
        "Perez-Salinas et al., Data Re-uploading for a Universal Quantum Classifier",
        2020,
        "primary variational QML research",
        "Synthetic single- and multi-qubit classification",
        "https://quantum-journal.org/papers/q-2020-02-06-226/",
        "10.22331/q-2020-02-06-226",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Classify complex low-dimensional datasets",
        uncertainty_treatment="Repeated benchmark examples; no mission uncertainty",
        input_data_and_availability="Synthetic benchmark datasets; public code linked",
        classical_algorithm="One-hidden-layer neural-network comparison",
        quantum_algorithm="RY-like data re-uploading with trainable processing units",
        quantum_resources="Single- and multi-qubit simulations, depth/layer trade-off, entanglement extension",
        optimizer_and_tuning="Classical optimization of circuit parameters",
        split_and_leakage_controls="Benchmark-specific; not a mission split",
        classical_baselines="One-hidden-layer neural network",
        primary_metrics="Classification success",
        uncertainty_and_statistics="No hardware or mission-level uncertainty claim",
        hardware_vs_simulation="Classical simulation",
        code_availability="public",
        failure_reporting="Explicitly says one-qubit results cannot provide quantum advantage",
        reported_limitations="Classification study; regression transfer requires direct validation",
        gate4_implication="Register data re-uploading but require 4/6/8-qubit and matched MLP comparisons",
        quality_baseline_fairness="partial",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="weak",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E006",
        "Caro et al., Encoding-Dependent Generalization Bounds for Parametrized Quantum Circuits",
        2021,
        "QML learning-theory research",
        "Generalization bounds for data-encoding PQCs",
        "https://quantum-journal.org/papers/q-2021-11-17-582/",
        "10.22331/q-2021-11-17-582",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Bound generalization as a function of encoding and model complexity",
        uncertainty_treatment="Theoretical probabilistic bounds",
        input_data_and_availability="Theory and numerical illustrations",
        classical_algorithm="Learning-theory comparators",
        quantum_algorithm="Parameterized circuits with encoding-dependent hypothesis classes",
        quantum_resources="Encoding and gate dependence analyzed rather than hardware performance",
        optimizer_and_tuning="not_primary",
        split_and_leakage_controls="Train/test generalization setting",
        classical_baselines="theoretical",
        primary_metrics="Generalization error bounds",
        uncertainty_and_statistics="Formal probability bounds",
        hardware_vs_simulation="Theory and simulation",
        code_availability="unclear",
        failure_reporting="Shows capacity/encoding can weaken generalization guarantees",
        reported_limitations="Bounds do not prove practical advantage",
        gate4_implication="Freeze encoding and report learning curves rather than treating qubit count as capacity proof",
        quality_statistical_uncertainty="strong",
        quality_quantum_resource_reporting="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E007",
        "Grant et al., An Initialization Strategy for Addressing Barren Plateaus in Parametrized Quantum Circuits",
        2019,
        "primary QML optimization research",
        "Trainability of variational circuits",
        "https://quantum-journal.org/papers/q-2019-12-09-214/",
        "10.22331/q-2019-12-09-214",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Mitigate vanishing-gradient initialization failures",
        uncertainty_treatment="Random initialization and numerical experiments",
        input_data_and_availability="Synthetic circuit tasks",
        classical_algorithm="Classical optimizer around PQC",
        quantum_algorithm="Layerwise/identity-block initialization for PQCs",
        quantum_resources="Circuit depth and initialization behavior reported",
        optimizer_and_tuning="Initialization is the intervention",
        split_and_leakage_controls="not_applicable",
        classical_baselines="Alternative initializations",
        primary_metrics="Gradient/trainability and optimization performance",
        uncertainty_and_statistics="Multiple random initializations",
        hardware_vs_simulation="Simulation",
        code_availability="unclear",
        failure_reporting="Barren-plateau failure is central",
        reported_limitations="Trainability mitigation is not performance advantage",
        gate4_implication="Freeze small initialization range and retain nonconverged seeds",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="partial",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E008",
        "Zavoli and Federici, Reinforcement Learning for Low-Thrust Trajectory Design of Interplanetary Missions",
        2020,
        "primary classical RL research",
        "Interplanetary low-thrust trajectory design",
        "https://arxiv.org/abs/2008.08501",
        dynamics_fidelity="Simulated low-thrust interplanetary dynamics",
        objective_and_constraints="Learn transfer control under trajectory objectives",
        uncertainty_treatment="Simulation and training stochasticity; not human-rated uncertainty",
        input_data_and_availability="Simulated trajectories",
        classical_algorithm="Deep reinforcement learning",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="RL hyperparameters reported in paper",
        split_and_leakage_controls="Evaluation episodes; not frozen mission grouping",
        classical_baselines="Numerical trajectory references",
        primary_metrics="Transfer success, cost, and control performance",
        uncertainty_and_statistics="Seed reporting limited relative to this protocol",
        hardware_vs_simulation="Classical simulation",
        code_availability="public",
        failure_reporting="Training/convergence limits discussed",
        reported_limitations="Low-thrust interplanetary control differs from Orion correction prediction",
        gate4_implication="Retain as later control precedent, not a Phase 1 QML comparator",
        quality_physics_mission_fidelity="partial",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E009",
        "Izzo et al., Real-Time Guidance for Low-Thrust Transfers Using Deep Artificial Neural Networks",
        2021,
        "primary classical surrogate guidance research",
        "Low-thrust transfer guidance surrogate",
        "https://arc.aiaa.org/doi/10.2514/1.G005254",
        "10.2514/1.G005254",
        dynamics_fidelity="Optimized low-thrust transfer simulations",
        objective_and_constraints="Approximate optimal guidance/control in real time",
        uncertainty_treatment="Task-specific simulated variation",
        input_data_and_availability="Simulated optimizer solutions; full dataset availability unclear",
        classical_algorithm="Deep artificial neural network",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="Paper-specific supervised training",
        split_and_leakage_controls="Reported evaluation split; mission grouping not established",
        classical_baselines="Numerical optimal guidance",
        primary_metrics="Guidance approximation error and runtime",
        uncertainty_and_statistics="Limited transfer to human-rated cislunar uncertainty",
        hardware_vs_simulation="Classical simulation",
        code_availability="not_verified_public",
        failure_reporting="Domain and generalization boundaries reported",
        reported_limitations="Different propulsion regime and mission task",
        gate4_implication="Supports MLP baseline and independent repropagation requirement",
        quality_physics_mission_fidelity="partial",
    ),
    evidence(
        "E010",
        "Sullivan et al., Multi-Objective Reinforcement Learning for Low-Thrust Transfer Design Between Libration Point Orbits",
        2021,
        "primary cislunar RL research",
        "Earth-Moon CR3BP low-thrust transfers between libration-point orbits",
        "https://ntrs.nasa.gov/api/citations/20210018983/downloads/Multi_Objective_Reinforcement_Learning_for_Low_Thrust_Transfer_Design_between_Libration_Point_Orbits.pdf",
        dynamics_fidelity="Earth-Moon CR3BP with low-thrust acceleration and mass flow",
        objective_and_constraints="Multi-objective flight time and propellant use",
        uncertainty_treatment="Training stochasticity; no crewed mission covariance",
        input_data_and_availability="Simulated transfers",
        classical_algorithm="Multi-Reward PPO with moving reference",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="PPO/MRPPO settings and grid-search lineage reported",
        split_and_leakage_controls="Policy evaluation; not supervised grouped holdout",
        classical_baselines="Gradient-descent local optima",
        primary_metrics="Recovered solution-space objectives",
        uncertainty_and_statistics="Multiple policies/agents; limited confirmatory seed reporting",
        hardware_vs_simulation="Classical simulation",
        code_availability="not_verified_public",
        failure_reporting="Need for a reference trajectory and convergence difficulty are explicit",
        reported_limitations="SmallSat low-thrust design, not Orion correction-burn planning",
        gate4_implication="Supports cislunar classical baseline and explicit nonconvergence retention",
        quality_physics_mission_fidelity="partial",
        quality_baseline_fairness="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E011",
        "Steffen, Falck, and Faller, Q-Law for Rapid Assessment of Low-Thrust Cislunar Trajectories via Automatic Differentiation",
        2025,
        "primary cislunar guidance research",
        "Rapid low-thrust cislunar trajectory assessment",
        "https://ntrs.nasa.gov/api/citations/20240016341/downloads/Nate_Steffen_AAS_Final_Manuscript_with_copyright.pdf",
        dynamics_fidelity="Cislunar low-thrust guidance approximation",
        objective_and_constraints="Rapid trajectory assessment under Q-law guidance",
        uncertainty_treatment="Sensitivity-focused rather than Artemis covariance",
        input_data_and_availability="NASA technical manuscript",
        classical_algorithm="Automatic-differentiation Q-law guidance",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="Guidance parameters described in source",
        split_and_leakage_controls="not_a_supervised_benchmark",
        classical_baselines="Numerical cislunar trajectories",
        primary_metrics="Trajectory feasibility/cost and speed",
        uncertainty_and_statistics="No human-rated confirmatory distribution",
        hardware_vs_simulation="Classical simulation",
        code_availability="not_verified_public",
        failure_reporting="Approximation/domain limits discussed",
        reported_limitations="Low-thrust model is a transferable low-fidelity reference, not Orion truth",
        gate4_implication="Supports physics-derived features and low-fidelity residual comparator",
        quality_physics_mission_fidelity="partial",
    ),
    evidence(
        "E012",
        "NASA, NASA-STD-7009B Standard for Models and Simulations",
        2024,
        "authoritative technical standard",
        "NASA model and simulation credibility",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/1/NASA-STD-7009B-Final-3-5-2024.pdf",
        dynamics_fidelity="applies_across_model_fidelities",
        objective_and_constraints="Credibility, verification, validation, uncertainty, and use-boundary requirements",
        uncertainty_treatment="Requires explicit uncertainty and evidence handling",
        input_data_and_availability="Public NASA standard",
        classical_algorithm="not_applicable",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="not_applicable",
        split_and_leakage_controls="Supports independent validation and intended-use controls",
        classical_baselines="not_applicable",
        primary_metrics="Credibility evidence rather than predictive score",
        uncertainty_and_statistics="Requires justified uncertainty treatment",
        hardware_vs_simulation="not_applicable",
        code_availability="not_applicable",
        failure_reporting="Credibility gaps and limitations must be retained",
        reported_limitations="Standard does not certify this model or supply mission data",
        gate4_implication="Governs data card, intended use, validation evidence, and claim boundary",
        quality_data_provenance="strong",
        quality_physics_mission_fidelity="strong",
        quality_baseline_fairness="not_applicable",
        quality_split_leakage="not_applicable",
        quality_statistical_uncertainty="strong",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E013",
        "NASA, NASA-STD-3001 Volume 2 Revision E",
        2025,
        "authoritative human-system standard",
        "Crew health, performance, habitability, and environmental constraints",
        "https://standards.nasa.gov/standard/NASA/NASA-STD-3001_VOL_2",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Agency-level human-system requirements for human-rated systems",
        uncertainty_treatment="Requirements and application boundaries rather than statistical model",
        input_data_and_availability="Active public NASA standard dated 2025-05-01",
        classical_algorithm="not_applicable",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="not_applicable",
        split_and_leakage_controls="not_applicable",
        classical_baselines="not_applicable",
        primary_metrics="Human-system compliance",
        uncertainty_and_statistics="Requirement-specific",
        hardware_vs_simulation="not_applicable",
        code_availability="not_applicable",
        failure_reporting="Noncompliance must remain a hard gate",
        reported_limitations="Public standard is not an Orion mission-specific operational waiver or threshold source",
        gate4_implication="Keep sleep/acceleration constraints separate from prediction score and apply conservative assumptions",
        quality_data_provenance="strong",
        quality_physics_mission_fidelity="strong",
        quality_baseline_fairness="not_applicable",
        quality_split_leakage="not_applicable",
        quality_statistical_uncertainty="strong",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E014",
        "Xie and Dempster, Feasible Low-Thrust Trajectory Identification via a Deep Neural Network Classifier",
        2022,
        "primary classical surrogate research",
        "Pre-optimization feasibility classification for low-thrust transfers",
        "https://arxiv.org/abs/2202.04962",
        dynamics_fidelity="Simulated low-thrust optimization cases",
        objective_and_constraints="Predict optimization convergence/feasibility before expensive solves",
        uncertainty_treatment="Randomly initialized transfer cases",
        input_data_and_availability="Simulated trajectory-optimization data; code not identified",
        classical_algorithm="DNN classifier with tested classical alternatives",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="Paper-specific model comparison",
        split_and_leakage_controls="Reported held-out classification evaluation; group leakage controls unclear",
        classical_baselines="Multiple tested classifiers",
        primary_metrics="Classification accuracy reported as 97.9 percent for DNN",
        uncertainty_and_statistics="Aggregate classification metrics; limited seed reporting",
        hardware_vs_simulation="Classical simulation",
        code_availability="not_identified",
        failure_reporting="Infeasible optimizer cases are the target rather than discarded",
        reported_limitations="Low-thrust convergence label is not Orion flight feasibility",
        gate4_implication="Keep every nonconvergence outcome and train an explicit feasibility head",
        quality_physics_mission_fidelity="partial",
        quality_split_leakage="unclear",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E015",
        "Zhang and Topputo, Neural Approximators for Low-Thrust Trajectory Transfer Cost and Reachability",
        2025,
        "primary classical surrogate preprint",
        "General low-thrust transfer cost and reachability prediction",
        "https://arxiv.org/abs/2508.02911",
        dynamics_fidelity="Optimized low-thrust transfer datasets across orbital environments",
        objective_and_constraints="Predict velocity increment, transfer time, and reachability",
        uncertainty_treatment="Cross-domain and third-party validation rather than operational uncertainty",
        input_data_and_availability="Large simulated dataset; authors report C++, Python, and MATLAB implementations",
        classical_algorithm="Pretrained neural approximators with self-similar transformation",
        quantum_algorithm="not_applicable",
        quantum_resources="not_applicable",
        optimizer_and_tuning="Scaling-law study over dataset/model size",
        split_and_leakage_controls="Third-party and mission-analysis validation reported; exact grouping requires inspection",
        classical_baselines="Trajectory optimizers and prior approximators",
        primary_metrics="Relative velocity-increment and minimum-time errors",
        uncertainty_and_statistics="Learning-scaling and external-validation evidence",
        hardware_vs_simulation="Classical simulation",
        code_availability="reported_public",
        failure_reporting="Reachability is a separate output",
        reported_limitations="Preprint and low-thrust domain; not crewed cislunar correction truth",
        gate4_implication="Use cost plus feasibility outputs, learning curves, physics scaling, and external grouped tests",
        quality_physics_mission_fidelity="partial",
        quality_reproducibility="strong",
        quality_claim_calibration="partial",
    ),
    evidence(
        "E016",
        "Otten et al., Quantum Machine Learning Using Gaussian Processes with Performant Quantum Kernels",
        2020,
        "primary quantum-kernel research",
        "One- and multidimensional regression plus reinforcement-learning demonstrations",
        "https://arxiv.org/abs/2004.11280",
        dynamics_fidelity="Generic regression/control tasks",
        objective_and_constraints="Construct quantum-enhanced kernels inspired by performant classical kernels",
        uncertainty_treatment="Gaussian-process predictive setting",
        input_data_and_availability="Paper benchmark tasks",
        classical_algorithm="Gaussian processes with classical kernels",
        quantum_algorithm="Quantum kernels embedded in Gaussian processes",
        quantum_resources="Simulation and quantum hardware demonstrations; task-specific circuits",
        optimizer_and_tuning="Kernel design is informed by classical inductive bias",
        split_and_leakage_controls="Benchmark-specific; mission grouping absent",
        classical_baselines="Classical inspiration kernels",
        primary_metrics="Regression/control prediction performance",
        uncertainty_and_statistics="GP uncertainty; broad advantage claims remain task-specific",
        hardware_vs_simulation="Both simulation and hardware",
        code_availability="unclear",
        failure_reporting="States unsimulability is necessary but insufficient for advantage",
        reported_limitations="Generic tasks and designed kernels do not establish cislunar benefit",
        gate4_implication="Register quantum kernel regression but tune inductive bias and compare to GP/RBF baselines",
        quality_baseline_fairness="partial",
        quality_quantum_resource_reporting="partial",
        quality_hardware_realism="strong",
        quality_claim_calibration="partial",
    ),
    evidence(
        "E017",
        "Sweke et al., Potential and Limitations of Random Fourier Features for Dequantizing Quantum Machine Learning",
        2025,
        "QML dequantization theory",
        "Variational-QML regression and classical random-feature approximation",
        "https://arxiv.org/abs/2309.11647",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Characterize when RFF linear regression efficiently approximates PQC regression",
        uncertainty_treatment="Formal sample-complexity and approximation statements",
        input_data_and_availability="Theory with architecture-dependent conditions",
        classical_algorithm="Random Fourier feature regression",
        quantum_algorithm="Variational PQC regression",
        quantum_resources="Circuit architecture and Fourier structure determine dequantization conditions",
        optimizer_and_tuning="Architecture-dependent",
        split_and_leakage_controls="Statistical-learning formulation",
        classical_baselines="RFF and tensor-network-motivated classical models",
        primary_metrics="Risk gap and sample/feature complexity",
        uncertainty_and_statistics="Formal high-probability bounds",
        hardware_vs_simulation="Theory; no hardware advantage demonstration",
        code_availability="unclear",
        failure_reporting="Explicitly identifies efficiently dequantizable regimes and unresolved worst cases",
        reported_limitations="Conditions can be hard to verify without solving the learning problem",
        gate4_implication="Add matched random-feature/classical residual controls before any quantum claim",
        quality_baseline_fairness="strong",
        quality_statistical_uncertainty="strong",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="not_applicable",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E018",
        "Peters and Schuld, Generalization Despite Overfitting in Quantum Machine Learning Models",
        2023,
        "QML learning-theory research",
        "Regression on noisy signals with quantum/Fourier models",
        "https://arxiv.org/abs/2209.05523",
        "10.22331/q-2023-12-20-1210",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Characterize benign overfitting in quantum regression models",
        uncertainty_treatment="Noisy signals and interpolation behavior",
        input_data_and_availability="Theory plus demonstration example",
        classical_algorithm="Interpolating Fourier-feature regression",
        quantum_algorithm="Quantum models linked to encoding/state-preparation structure",
        quantum_resources="Circuit structure analyzed; no hardware benchmark",
        optimizer_and_tuning="not_primary",
        split_and_leakage_controls="Generalization setting",
        classical_baselines="Classical Fourier-feature model",
        primary_metrics="Generalization under noisy interpolation",
        uncertainty_and_statistics="Noise/generalization theory",
        hardware_vs_simulation="Theory and demonstration",
        code_availability="unclear",
        failure_reporting="Overfitting is not treated as automatic failure or success",
        reported_limitations="Theory does not replace held-out mission testing",
        gate4_implication="Report learning curves and held-out errors; never infer generalization from training fit",
        quality_statistical_uncertainty="strong",
        quality_quantum_resource_reporting="partial",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E019",
        "Shaydulin and Wild, Importance of Kernel Bandwidth in Quantum Machine Learning",
        2022,
        "primary quantum-kernel benchmark",
        "Quantum-kernel classification and regression behavior",
        "https://arxiv.org/abs/2111.05451",
        "10.1103/PhysRevA.106.042407",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Control quantum-kernel inductive bias through bandwidth",
        uncertainty_treatment="Multiple datasets and numerical repetitions",
        input_data_and_availability="Classical datasets; raw data and code released",
        classical_algorithm="SVC/kernel ridge and best classical methods",
        quantum_algorithm="Quantum feature-map kernel",
        quantum_resources="Multiple feature maps and qubit-scaling experiments",
        optimizer_and_tuning="Bandwidth is explicitly tuned by cross-validation",
        split_and_leakage_controls="Cross-validation; mission grouping absent",
        classical_baselines="Best classical methods and reproduced negative quantum result",
        primary_metrics="Prediction accuracy and kernel spectrum/generalization",
        uncertainty_and_statistics="Dataset-level comparisons",
        hardware_vs_simulation="Numerical quantum-kernel experiments",
        code_availability="public",
        failure_reporting="Reproduces degradation with qubit count before bandwidth correction",
        reported_limitations="Competitive performance after tuning is not quantum advantage",
        gate4_implication="Treat encoding scale/bandwidth as frozen tuning parameters and report negative scaling",
        quality_baseline_fairness="strong",
        quality_split_leakage="partial",
        quality_quantum_resource_reporting="strong",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E020",
        "Pernot, Huang, and Savin, Impact of Non-Normal Error Distributions on the Benchmarking and Ranking of Quantum Machine Learning Models",
        2020,
        "primary statistical benchmark analysis",
        "Atomistic kernel-regression error distributions",
        "https://arxiv.org/abs/2004.02524",
        "10.1088/2632-2153/aba184",
        dynamics_fidelity="Atomistic simulation, not trajectory dynamics",
        objective_and_constraints="Assess model ranking when prediction errors are non-normal",
        uncertainty_treatment="Empirical residual-distribution analysis",
        input_data_and_availability="QM7b and calculated reference methods",
        classical_algorithm="Kernel ridge regression with SLATM representation",
        quantum_algorithm="No quantum circuit; QML here means ML for quantum chemistry",
        quantum_resources="not_applicable",
        optimizer_and_tuning="Learning-set adaptation analyzed",
        split_and_leakage_controls="Dataset benchmark; transfer of outliers into training illustrates selection sensitivity",
        classical_baselines="HF and MP2 reference errors",
        primary_metrics="MAE and residual-distribution diagnostics",
        uncertainty_and_statistics="Shows MAE can mis-rank non-normal errors",
        hardware_vs_simulation="Classical computation",
        code_availability="unclear",
        failure_reporting="Tail/outlier behavior is central",
        reported_limitations="Terminology differs from gate-based QML and domain is chemistry",
        gate4_implication="Report RMSE, MAE, tails, CVaR, and seed rows rather than a single average",
        quality_baseline_fairness="strong",
        quality_statistical_uncertainty="strong",
        quality_quantum_resource_reporting="not_applicable",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E021",
        "Havlicek et al., Supervised Learning with Quantum-Enhanced Feature Spaces",
        2019,
        "primary quantum-kernel hardware research",
        "Small supervised classification feature-space demonstration",
        "https://www.nature.com/articles/s41586-019-0980-2",
        "10.1038/s41586-019-0980-2",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Use quantum feature maps for classification",
        uncertainty_treatment="Finite experimental data and device noise",
        input_data_and_availability="Engineered small classification data",
        classical_algorithm="Classical kernel/SVM processing",
        quantum_algorithm="Quantum feature-space kernel and variational classifier",
        quantum_resources="Small superconducting-processor demonstration",
        optimizer_and_tuning="Task-specific feature map",
        split_and_leakage_controls="Small benchmark split",
        classical_baselines="Classical supervised methods",
        primary_metrics="Classification accuracy",
        uncertainty_and_statistics="Limited small-sample hardware evidence",
        hardware_vs_simulation="Quantum hardware and simulation",
        code_availability="partial_or_linked",
        failure_reporting="Noise/small-scale limits constrain interpretation",
        reported_limitations="Engineered classification task does not establish trajectory-regression advantage",
        gate4_implication="Include finite-shot/noise conditions but classify hardware claims as external validation only",
        quality_baseline_fairness="partial",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="strong",
        quality_claim_calibration="partial",
    ),
    evidence(
        "E022",
        "Schuld and Killoran, Quantum Machine Learning in Feature Hilbert Spaces",
        2019,
        "QML theory and method research",
        "Quantum feature maps and kernel/variational learning",
        "https://arxiv.org/abs/1803.07128",
        "10.1103/PhysRevLett.122.040504",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Relate quantum encoding to feature maps and kernel methods",
        uncertainty_treatment="not_primary",
        input_data_and_availability="Two-dimensional mini-benchmark illustrations",
        classical_algorithm="Classical kernel method over quantum-computed inner products",
        quantum_algorithm="Quantum kernel estimation and variational linear model in Hilbert space",
        quantum_resources="Continuous-variable example and conceptual near-term device path",
        optimizer_and_tuning="Task-specific",
        split_and_leakage_controls="Mini-benchmark only",
        classical_baselines="Kernel-method framing",
        primary_metrics="Illustrative classification",
        uncertainty_and_statistics="No practical advantage test",
        hardware_vs_simulation="Theory/illustration",
        code_availability="unclear",
        failure_reporting="No broad empirical advantage claim",
        reported_limitations="Foundational mechanism, not evidence of application benefit",
        gate4_implication="Use overlap kernel with explicit classical kernel comparator and encoding report",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="partial",
        quality_claim_calibration="strong",
    ),
    evidence(
        "E023",
        "Huang et al., Power of Data in Quantum Machine Learning",
        2021,
        "QML theory and large numerical benchmark",
        "Assessment of when data lets classical models match quantum models",
        "https://www.nature.com/articles/s41467-021-22539-9",
        "10.1038/s41467-021-22539-9",
        dynamics_fidelity="not_applicable",
        objective_and_constraints="Bound and test prediction advantage for quantum versus classical learning",
        uncertainty_treatment="Prediction-error bounds and numerical experiments",
        input_data_and_availability="Engineered quantum-learning datasets and source data",
        classical_algorithm="Classical kernel models and classical approximations of quantum models",
        quantum_algorithm="Quantum and projected quantum kernels",
        quantum_resources="Numerical tests up to 30 qubits on engineered tasks",
        optimizer_and_tuning="Embedding/task alignment is central",
        split_and_leakage_controls="Supervised-learning train/test framework",
        classical_baselines="Classical ML and approximations of quantum models",
        primary_metrics="Prediction error and geometric advantage indicators",
        uncertainty_and_statistics="Rigorous asymptotic and empirical bounds",
        hardware_vs_simulation="Theory and classical numerical simulation",
        code_availability="reported_open_source",
        failure_reporting="Shows hard-to-compute circuits can still be learnable by classical models from data",
        reported_limitations="Advantage examples use engineered data and need practical validation",
        gate4_implication="Require classical approximations, task alignment checks, and no advantage language for simulation",
        quality_data_provenance="strong",
        quality_baseline_fairness="strong",
        quality_split_leakage="strong",
        quality_statistical_uncertainty="strong",
        quality_quantum_resource_reporting="strong",
        quality_hardware_realism="partial",
        quality_reproducibility="strong",
        quality_claim_calibration="strong",
    ),
]


def normalize_title(value: str) -> str:
    return " ".join(
        "".join(
            character.lower() if character.isalnum() else " " for character in value
        ).split()
    )


def write_csv(
    path: Path, rows: list[Mapping[str, Any]], fields: tuple[str, ...]
) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def update_screening() -> None:
    path = LITERATURE / "screening_log.csv"
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        fields = tuple(reader.fieldnames or ())

    included = {normalize_title(row["citation"].split(", ", 1)[-1]) for row in RECORDS}
    # Citation prefixes make exact extraction unreliable; source titles provide
    # a second stable set for all records already present in the seed matrix.
    included.update(
        {
            normalize_title(
                "Optimized Trajectory Correction Burn Placement for the NASA Artemis II Mission"
            ),
            normalize_title(
                "Transcription and optimization of an interplanetary trajectory through quantum annealing"
            ),
            normalize_title(
                "Better than classical? The subtle art of benchmarking quantum machine learning models"
            ),
            normalize_title(
                "Quantum agents in the Gym: a variational quantum algorithm for deep Q-learning"
            ),
            normalize_title("Data re-uploading for a universal quantum classifier"),
            normalize_title(
                "Encoding-dependent generalization bounds for parametrized quantum circuits"
            ),
            normalize_title(
                "An initialization strategy for addressing barren plateaus in parametrized quantum circuits"
            ),
            normalize_title(
                "Reinforcement Learning for Low-Thrust Trajectory Design of Interplanetary Missions"
            ),
            normalize_title(
                "Real-Time Guidance for Low-Thrust Transfers Using Deep Artificial Neural Networks"
            ),
            normalize_title(
                "Multi-Objective Reinforcement Learning for Low-Thrust Transfer Design Between Libration Point Orbits"
            ),
            normalize_title(
                "Q-Law for Rapid Assessment of Low Thrust Cislunar Trajectories via Automatic Differentiation"
            ),
            normalize_title("NASA-STD-7009B Standard for Models and Simulations"),
            normalize_title("NASA-STD-3001 Volume 2 Revision E"),
            normalize_title(
                "Feasible Low-thrust Trajectory Identification via a Deep Neural Network Classifier"
            ),
            normalize_title(
                "Neural Approximators for Low-Thrust Trajectory Transfer Cost and Reachability"
            ),
            normalize_title(
                "Quantum Machine Learning using Gaussian Processes with Performant Quantum Kernels"
            ),
            normalize_title(
                "Potential and limitations of random Fourier features for dequantizing quantum machine learning"
            ),
            normalize_title(
                "Generalization despite overfitting in quantum machine learning models"
            ),
            normalize_title(
                "Importance of Kernel Bandwidth in Quantum Machine Learning"
            ),
            normalize_title(
                "Impact of non-normal error distributions on the benchmarking and ranking of Quantum Machine Learning models"
            ),
        }
    )

    for row in rows:
        title = normalize_title(row["title"])
        if title in included or "seed:" in row["source_record_ids"]:
            row["stage"] = "primary_or_authoritative_record_screen"
            row["decision"] = "include"
            row["exclusion_reason"] = ""
            row["full_text_status"] = "included_and_extracted"
        elif row["decision"] == "include_for_full_text":
            searches = set(row["search_ids"].split(";"))
            if searches & {"S1", "S2", "S5"}:
                row["stage"] = "title_abstract_second_pass"
                row["decision"] = "defer_phase_6"
                row["exclusion_reason"] = (
                    "control_or_mission_design_record_not_needed_for_phase_1_prediction_freeze"
                )
                row["full_text_status"] = "deferred_without_phase_1_claim"
            else:
                row["stage"] = "title_abstract_second_pass"
                row["decision"] = "exclude"
                row["exclusion_reason"] = (
                    "does_not_directly_inform_registered_phase_1_models_fairness_or_statistics"
                )
                row["full_text_status"] = "not_requested_after_second_pass"

    supplemental = [
        (
            "Supervised learning with quantum-enhanced feature spaces",
            2019,
            "10.1038/s41586-019-0980-2",
            "https://www.nature.com/articles/s41586-019-0980-2",
            "reference_chain:E005",
        ),
        (
            "Quantum Machine Learning in Feature Hilbert Spaces",
            2019,
            "10.1103/PhysRevLett.122.040504",
            "https://arxiv.org/abs/1803.07128",
            "reference_chain:E005",
        ),
        (
            "Power of data in quantum machine learning",
            2021,
            "10.1038/s41467-021-22539-9",
            "https://www.nature.com/articles/s41467-021-22539-9",
            "reference_chain:E003",
        ),
    ]
    existing = {normalize_title(row["title"]) for row in rows}
    for title, year, doi, url, record_id in supplemental:
        if normalize_title(title) in existing:
            continue
        rows.append(
            {
                "screening_id": f"SCR{len(rows) + 1:05d}",
                "canonical_key": f"doi:{doi.lower()}",
                "title": title,
                "year": year,
                "doi": doi.lower(),
                "source_record_ids": record_id,
                "databases": "primary-source reference chain",
                "search_ids": "S3",
                "stage": "primary_or_authoritative_record_screen",
                "decision": "include",
                "exclusion_reason": "",
                "full_text_status": "included_and_extracted",
                "url": url,
            }
        )
    write_csv(path, rows, fields)


def main() -> None:
    if len({row["evidence_id"] for row in RECORDS}) != len(RECORDS):
        raise ValueError("Extraction evidence IDs must be unique")
    write_csv(LITERATURE / "extraction_matrix.csv", RECORDS, FIELDS)
    update_screening()
    print(f"Wrote {len(RECORDS)} fully extracted evidence records.")


if __name__ == "__main__":
    main()
